package org.ar25.androidno.entities


import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType
import org.ar25.androidno.db.DbOpenHelper.Companion.DB_POSTS_TABLE


@StorIOSQLiteType(table = DB_POSTS_TABLE)
data class Post(

        @JvmField @StorIOSQLiteColumn(name = DB_POSTS_ID, key = true)
        var id: Long,

        @JvmField @StorIOSQLiteColumn(name = DB_POSTS_HEADER)
        var header: String,

        @JvmField @StorIOSQLiteColumn(name = DB_POSTS_PUBLISH_DATE)
        var publishDate: String,

        @JvmField @StorIOSQLiteColumn(name = DB_POSTS_IMAGE_URL)
        var imageUrl: String,

        @JvmField @StorIOSQLiteColumn(name = DB_POSTS_TEASER)
        var teaser: String,

        @JvmField @StorIOSQLiteColumn(name = DB_POSTS_TEXT)
        var text: String? = null  ){

    internal constructor() : this(-1, "", "", "", "") { } // leave default constructor for AutoGenerated code
}